version: '3'

services:
  ${APP_CONTAINER_NAME}:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${APP_CONTAINER_IMAGE}:${IMAGE_ID}
    command: npx directus start
    working_dir: /directus
    env_file:
      - ../../../../.env
    ports:
      - 8055:8055
    expose:
      - 8055
    logging:
      driver: awslogs
      options:
        awslogs-group: ${APP_AWS_LOG_GROUP}
        awslogs-region: ${REGION}
        awslogs-stream-prefix: ecs
